# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BookMarker' do
  
  use_frameworks!

  pod 'SDWebImageSwiftUI'
  pod 'RealmSwift'
  pod 'ToastSwiftUI'

end
